# Gradle
org.gradle.jvmargs=-Xmx8G
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Minecraft / NeoForge
minecraft_version=1.21.1
neo_version=21.1.219

# Mod
mod.version=1.0.10
mod.license=MIT
mod.group=toni
mod.namespace=sodiumdynamiclights
mod.id=sodiumdynamiclights
mod.name=SodiumDynamicLights
mod.archive_name=SodiumDynamicLights-KaenguruuDev
mod.author=KaenguruuDev
mod.github=txnimc
mod.display_name=Sodium Dynamic Lights
mod.description=KaenguruuDev's fork of Sodium Dynamic Lights for Sodium on NeoForge 1.21.1. Original work by toni and LambdAurora.
mod.discord=https://discord.gg/kS7auUeYmc

# Dependencies
sodium_version=Pb3OXVqC
mixinsquared_version=0.2.0-beta.6
