modLoader = "javafml"
loaderVersion="[1,)"
license="${license}"
showAsResourcePack=false

issueTrackerURL = "https://github.com/${github}/${name}/issues"

[[mods]]
modId="${id}"
version="${modversion}"
displayName="${display_name}"
authors="${author} (fork maintainer), toni, LambdAurora"
description="${description}"
logoFile="assets/${namespace}/textures/mod_logo.png"
displayURL = "https://github.com/${github}/${name}/"

[modproperties.${id}]
"sodium:config_api_user" = "toni.sodiumdynamiclights.SodiumDynamicLightsConfigEntrypoint"

[[mixins]]
config = "mixins.${id}.json"

[[dependencies."${id}"]]
modId="minecraft"
mandatory=true
versionRange="${mc}"
ordering="NONE"
side="BOTH"

[[dependencies."${id}"]]
modId="sodium"
mandatory=true
versionRange="[0.8.13-beta.2,)"
ordering="AFTER"
side="CLIENT"
